name: main build_viash_hub
concurrency: main_build_viash_hub

on:
  push:
    branches: [ 'main', 'feature/push_viashhub' ]

jobs:
  # phase 1
  list:
    runs-on: ubuntu-latest

    outputs:
      component_matrix: ${{ steps.set_matrix.outputs.matrix }}
      cache_key: ${{ steps.cache.outputs.cache_key }}

    steps:
    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v4

    - name: Remove target folder from .gitignore
      run: |
        # allow publishing the target folder
        sed -i '/^\/target\/$/d' .gitignore

    - uses: viash-io/viash-actions/ns-build@v4
      with:
        config_mod: .functionality.version := 'main_build'; .platforms[.type == 'docker'].target_registry := 'viash-hub.com:5050'; .platforms[.type == 'docker'].target_organization := 'openpipelines-bio/openpipeline'; .platforms[.type == 'docker'].target_image_source := 'https://github.com/openpipelines-bio/openpipeline'
        parallel: true

    - name: Build nextflow schemas
      uses: viash-io/viash-actions/pro/build-nextflow-schemas@v4
      with:
        workflows: workflows
        components: src
        viash_pro_token: ${{ secrets.GTHB_PAT }}
        tools_version: 'main_build'
   
    - name: Build parameter files
      uses: viash-io/viash-actions/pro/build-nextflow-params@v4
      with:
        workflows: workflows
        components: src
        viash_pro_token: ${{ secrets.GTHB_PAT }}
        tools_version: 'main_build'

    - name: Deploy to target branch
      uses: peaceiris/actions-gh-pages@v3.9.3
      env:
        GITHUB_SERVER_URL: 'https://viash-hub.com'
      with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        personal_token: ${{ secrets.VIASHHUB_PAT}}
        publish_dir: .
        publish_branch: main_build
        exclude_assets: ''

    - id: ns_list
      uses: viash-io/viash-actions/ns-list@v4
      with:
        platform: docker
        src: src
        format: json

    - id: set_matrix
      run: |
        echo "matrix=$(jq -c '[ .[] | 
          { 
            "name": (.functionality.namespace + "/" + .functionality.name),
            "config": .info.config,
            "dir": .info.config | capture("^(?<dir>.*\/)").dir
          }
        ]' ${{ steps.ns_list.outputs.output_file }} )" >> $GITHUB_OUTPUT

  # phase 2
  build:
    needs: list

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        component: ${{ fromJson(needs.list.outputs.component_matrix) }}

    steps:
    # Remove unnecessary files to free up space. Otherwise, we get 'no space left on device.'
    - uses: data-intuitive/reclaim-the-bytes@v2

    - uses: actions/checkout@v3

    - uses: viash-io/viash-actions/setup@v4

    - name: Build container
      uses: viash-io/viash-actions/ns-build@v4
      with:
        config_mod: .functionality.version := 'main_build'; .platforms[.type == 'docker'].target_registry := 'viash-hub.com:5050'; .platforms[.type == 'docker'].target_organization := 'openpipelines-bio/openpipeline'; .platforms[.type == 'docker'].target_image_source := 'https://github.com/openpipelines-bio/openpipeline'
        platform: docker
        src: ${{ matrix.component.dir }}
        setup: build

    - name: Login to Viash-Hub container registry
      uses: docker/login-action@v2
      with:
        registry: viash-hub.com:5050
        username: ${{ secrets.VIASHHUB_USER }}
        password: ${{ secrets.VIASHHUB_PAT }}

    - name: Push container to Viash-Hub
      uses: viash-io/viash-actions/ns-build@v4
      with:
        config_mod: .functionality.version := 'main_build'; .platforms[.type == 'docker'].target_registry := 'viash-hub.com:5050'; .platforms[.type == 'docker'].target_organization := 'openpipelines-bio/openpipeline'; .platforms[.type == 'docker'].target_image_source := 'https://github.com/openpipelines-bio/openpipeline'
        platform: docker
        src: ${{ matrix.component.dir }}
        setup: push
